tools:
    external_code_coverage:
        timeout: 3000  # Timeout in seconds
        runs: 2        # Scrutinizer will wait for code coverage of unit and functional tests
    php_cpd: true
    php_pdepend: true
    php_changetracking: true
    sensiolabs_security_checker: true
