<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2009-07-31 16:16

$extensionClassesPath = t3lib_extMgm::extPath('mvc_extjs') . 'Classes/';
return array(
	'tx_mvcextjs_backenddispatcher' => $extensionClassesPath . 'BackendDispatcher.php',
	'tx_mvcextjs_extjs_settingsservice' => $extensionClassesPath . 'ExtJS/SettingsService.php',
	'tx_mvcextjs_extjs_utility' => $extensionClassesPath . 'ExtJS/Utility.php',
	'tx_mvcextjs_extjs_controller_actioncontroller' => $extensionClassesPath . 'ExtJS/Controller/ActionController.php',
	'tx_mvcextjs_utility_module' => $extensionClassesPath . 'Utility/Module.php',
	'tx_mvcextjs_viewhelpers_nullviewhelper' => $extensionClassesPath . 'ViewHelpers/NullViewHelper.php',
);
?>