<?php

########################################################################
# Extension Manager/Repository config file for ext: "newsletter"
#
# Auto generated by Extbase Kickstarter 2011-02-18
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Newsletter',
	'description' => 'Newsletter extension with simple to setup and use mailer',
	'category' => 'module',
	'author' => 'Adrien Crivelli, Fabien Udriot, Daniel Schledermann',
	'author_email' => 'adrien.crivelli@ecodev.ch, fabien.udriot@ecodev.ch, info@newsletter.dk',
	'author_company' => 'Ecodev, Casalogic A/S',
	'shy' => '',
	'conflicts' => '',
	'priority' => '',
	'module' => 'cli,web',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '1.1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'php' => '5.2.9-',
			'typo3' => '4.5.0-',
			'mvc_extjs' => '0.2.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);


