<?php

/* * *******************************************************************
 * Extension configuration file for ext "newsletter".
 *
 * Generated by ext 03-02-2015 08:58 UTC
 *
 * https://github.com/t3elmar/Ext
 * ******************************************************************* */

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Newsletter',
    'description' => 'Send any pages as Newsletter and provide statistics on opened emails and clicked links.',
    'category' => 'module',
    'shy' => 0,
    'version' => '2.3.0',
    'dependencies' => '',
    'conflicts' => '',
    'priority' => '',
    'loadOrder' => '',
    'module' => 'cli,web',
    'state' => 'stable',
    'uploadfolder' => 1,
    'createDirs' => '',
    'modify_tables' => '',
    'clearcacheonload' => 0,
    'lockType' => '',
    'author' => 'Ecodev',
    'author_email' => 'contact@ecodev.ch',
    'author_company' => 'Ecodev',
    'CGLcompliance' => null,
    'CGLcompliance_note' => null,
    'constraints' => array(
        'depends' => array(
            'cms' => '',
            'extbase' => '',
            'fluid' => '',
            'php' => '5.3.7-0.0.0',
            'typo3' => '6.1.0-7.0.99',
            'scheduler' => '1.1.0',
        ),
        'conflicts' => '',
        'suggests' => array(
        ),
    ),
);
