<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2010-01-21 12:45

$extensionClassesPath = t3lib_extMgm::extPath('mvc_extjs') . 'Classes/';
return array(
	'tx_mvcextjs_extjs_array' => $extensionClassesPath . 'ExtJS/Array.php',
	'tx_mvcextjs_extjs_formelement' => $extensionClassesPath . 'ExtJS/FormElement.php',
	'tx_mvcextjs_extjs_object' => $extensionClassesPath . 'ExtJS/Object.php',
	'tx_mvcextjs_extjs_propertytype' => $extensionClassesPath . 'ExtJS/PropertyType.php',
	'tx_mvcextjs_extjs_settingsservice' => $extensionClassesPath . 'ExtJS/SettingsService.php',
	'tx_mvcextjs_extjs_utility' => $extensionClassesPath . 'ExtJS/Utility.php',
	'tx_mvcextjs_extjs_controller_actioncontroller' => $extensionClassesPath . 'ExtJS/Controller/ActionController.php',
	'tx_mvcextjs_extjs_controller_extensionobjectactioncontroller' => $extensionClassesPath . 'ExtJS/Controller/ExtensionObjectActionController.php',
	'tx_mvcextjs_extjs_layout_toolbar' => $extensionClassesPath . 'ExtJS/Layout/Toolbar.php',
	'tx_mvcextjs_viewhelpers_jsonviewhelper' => $extensionClassesPath . 'ViewHelpers/JsonViewHelper.php',
	'tx_mvcextjs_viewhelpers_nullviewhelper' => $extensionClassesPath . 'ViewHelpers/NullViewHelper.php',
	'tx_mvcextjs_viewhelpers_be_includecssfileviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/IncludeCssFileViewHelper.php',
	'tx_mvcextjs_viewhelpers_be_includeextonreadycodeviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/IncludeExtOnReadyCodeViewHelper.php',
	'tx_mvcextjs_viewhelpers_be_includejsfileviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/IncludeJsFileViewHelper.php',
	'tx_mvcextjs_viewhelpers_be_includestoreviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/IncludeStoreViewHelper.php',
	'tx_mvcextjs_viewhelpers_be_modulecontainerviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/ModuleContainerViewHelper.php',
);
?>