<?php

/*                                                                        *
 * This script belongs to the FLOW3 package "Fluid".                      *
 *                                                                        *
 * It is free software; you can redistribute it and/or modify it under    *
 * the terms of the GNU Lesser General Public License as published by the *
 * Free Software Foundation, either version 3 of the License, or (at your *
 * option) any later version.                                             *
 *                                                                        *
 * This script is distributed in the hope that it will be useful, but     *
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-    *
 * TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser       *
 * General Public License for more details.                               *
 *                                                                        *
 * You should have received a copy of the GNU Lesser General Public       *
 * License along with the script.                                         *
 * If not, see http://www.gnu.org/licenses/lgpl.html                      *
 *                                                                        *
 * The TYPO3 project - inspiring people to share!                         *
 *                                                                        */

/**
 *
 *
 * @version $Id$
 * @package MvcExtjs
 * @subpackage ViewHelpers/Json
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License, version 3 or later
 */
class Tx_MvcExtjs_ViewHelpers_Json_MergeObjectsViewHelper extends Tx_Fluid_Core_ViewHelper_AbstractViewHelper implements Tx_Fluid_Core_Parser_SyntaxTree_RenderingContextAwareInterface { 
	
	/**
	 * Merges the nested json objects generated by other ViewHelpers together in one json object.
	 * TODO: only supports ViewHelpers that are written each per line...
	 *
	 * @return string merged json objects
	 * @author Dennis Ahrens <dennis.ahrens@fh-hannover.de>
	 */
	public function render() {
		$merged = array();
		$output = $this->renderChildren();
		$outputArray = explode("\n",$output);
		foreach ($outputArray as $line) {
			$jsonData = trim($line);
			$data = json_decode($jsonData,true);
			if ($data !== NULL) {
				$merged = array_merge($merged,$data);
			}
		}
		return json_encode($merged);
	}
}

?>
